export interface Pokemon {
  name: string;
  id: number;
  evolvesTo?: number; // id of evolved form if exists
}

export const POKEMON_LIST: Pokemon[] = [
  { name: 'bulbasaur', id: 1, evolvesTo: 2 },
  { name: 'ivysaur', id: 2, evolvesTo: 3 },
  { name: 'venusaur', id: 3 },
  { name: 'charmander', id: 4, evolvesTo: 5 },
  { name: 'charmeleon', id: 5, evolvesTo: 6 },
  { name: 'charizard', id: 6 },
  { name: 'squirtle', id: 7, evolvesTo: 8 },
  { name: 'wartortle', id: 8, evolvesTo: 9 },
  { name: 'blastoise', id: 9 },
    { name: 'caterpie', id: 10, evolvesTo: 11 },
    { name: 'metapod', id: 11, evolvesTo: 12 },
    { name: 'butterfree', id: 12 },
    { name: 'weedle', id: 13, evolvesTo: 14 },
    { name: 'kakuna', id: 14, evolvesTo: 15 },
    { name: 'beedrill', id: 15 },
    { name: 'pidgey', id: 16, evolvesTo: 17 },
    { name: 'pidgeotto', id: 17, evolvesTo: 18 },
    { name: 'pidgeot', id: 18 },
    { name: 'rattata', id: 19, evolvesTo: 20 },
    { name: 'raticate', id: 20 },
    { name: 'spearow', id: 21, evolvesTo: 22 },
    { name: 'fearow', id: 22 },
    { name: 'ekans', id: 23, evolvesTo: 24 },
    { name: 'arbok', id: 24 },
    { name: 'pikachu', id: 25, evolvesTo: 26 },
    { name: 'raichu', id: 26 },
    { name: 'sandshrew', id: 27, evolvesTo: 28 },
    { name: 'sandslash', id: 28 },
    { name: 'nidoran-f', id: 29, evolvesTo: 30 },
    { name: 'nidorina', id: 30, evolvesTo: 31 },
    { name: 'nidoqueen', id: 31 },
    { name: 'nidoran-m', id: 32, evolvesTo: 33 },
    { name: 'nidorino', id: 33, evolvesTo: 34 },
    { name: 'nidoking', id: 34 },
    { name: 'clefairy', id: 35, evolvesTo: 36 },
    { name: 'clefable', id: 36 },
    { name: 'vulpix', id: 37, evolvesTo: 38 },
    { name: 'ninetales', id: 38 },
    { name: 'jigglypuff', id: 39, evolvesTo: 40 },
    { name: 'wigglytuff', id: 40 },
    { name: 'zubat', id: 41, evolvesTo: 42 },
    { name: 'golbat', id: 42 },
    { name: 'oddish', id: 43, evolvesTo: 44 },
    { name: 'gloom', id: 44, evolvesTo: 45 },
    { name: 'vileplume', id: 45 },
    { name: 'paras', id: 46, evolvesTo: 47 },
    { name: 'parasect', id: 47 },
    { name: 'venonat', id: 48, evolvesTo: 49 },
    { name: 'venomoth', id: 49 },
    { name: 'diglett', id: 50, evolvesTo: 51 },
    { name: 'dugtrio', id: 51 },
    { name: 'meowth', id: 52, evolvesTo: 53 },
    { name: 'persian', id: 53 },
    { name: 'psyduck', id: 54, evolvesTo: 55 },
    { name: 'golduck', id: 55 },
    { name: 'mankey', id: 56, evolvesTo: 57 },
    { name: 'primeape', id: 57 },
    { name: 'growlithe', id: 58, evolvesTo: 59 },
    { name: 'arcanine', id: 59 },
    { name: 'poliwag', id: 60, evolvesTo: 61 },
    { name: 'poliwhirl', id: 61, evolvesTo: 62 },
    { name: 'poliwrath', id: 62 },
    { name: 'abra', id: 63, evolvesTo: 64 },
    { name: 'kadabra', id: 64, evolvesTo: 65 },
    { name: 'alakazam', id: 65 },
    { name: 'machop', id: 66, evolvesTo: 67 },
    { name: 'machoke', id: 67, evolvesTo: 68 },
    { name: 'machamp', id: 68 },
    { name: 'bellsprout', id: 69, evolvesTo: 70 },
    { name: 'weepinbell', id: 70, evolvesTo: 71 },
    { name: 'victreebel', id: 71 },
    { name: 'tentacool', id: 72, evolvesTo: 73 },
    { name: 'tentacruel', id: 73 },
    { name: 'geodude', id: 74, evolvesTo: 75 },
    { name: 'graveler', id: 75, evolvesTo: 76 },
    { name: 'golem', id: 76 },
    { name: 'ponyta', id: 77, evolvesTo: 78 },
    { name: 'rapidash', id: 78 },
    { name: 'slowpoke', id: 79, evolvesTo: 80 },
    { name: 'slowbro', id: 80 },
    { name: 'magnemite', id: 81, evolvesTo: 82 },
    { name: 'magneton', id: 82 },
    { name: 'farfetchd', id: 83 },
    { name: 'doduo', id: 84, evolvesTo: 85 },
    { name: 'dodrio', id: 85 },
    { name: 'seel', id: 86, evolvesTo: 87 },
    { name: 'dewgong', id: 87 },
    { name: 'grimer', id: 88, evolvesTo: 89 },
    { name: 'muk', id: 89 },
    { name: 'shellder', id: 90, evolvesTo: 91 },
    { name: 'cloyster', id: 91 },
    { name: 'gastly', id: 92, evolvesTo: 93 },
    { name: 'haunter', id: 93, evolvesTo: 94 },
    { name: 'gengar', id: 94 },
    { name: 'onix', id: 95 },
    { name: 'drowzee', id: 96 },
    { name: 'hypno', id: 97 },
    { name: 'krabby', id: 98 },
    { name: 'kingler', id: 99 },
    { name: 'voltorb', id: 100 },
    { name: 'electrode', id: 101 },
    { name: 'exeggcute', id: 102 },
    { name: 'exeggutor', id: 103 },
    { name: 'cubone', id: 104 },
    { name: 'marowak', id: 105 },
    { name: 'hitmonlee', id: 106 },
    { name: 'hitmonchan', id: 107 },
    { name: 'lickitung', id: 108 },
    { name: 'koffing', id: 109 },
    { name: 'weezing', id: 110 },
    { name: 'rhyhorn', id: 111 },
    { name: 'rhydon', id: 112 },
    { name: 'chansey', id: 113 },
    { name: 'tangela', id: 114 },
    { name: 'kangaskhan', id: 115 },
    { name: 'horsea', id: 116 },
    { name: 'seadra', id: 117 },
    { name: 'goldeen', id: 118 },
    { name: 'seaking', id: 119 },
    { name: 'staryu', id: 120 },
    { name: 'starmie', id: 121 },
    { name: 'mr-mime', id: 122 },
    { name: 'scyther', id: 123 },
    { name: 'jynx', id: 124 },
    { name: 'electabuzz', id: 125 },
    { name: 'magmar', id: 126 },
    { name: 'pinsir', id: 127 },
    { name: 'tauros', id: 128 },
    { name: 'magikarp', id: 129 },
    { name: 'gyarados', id: 130 },
    { name: 'lapras', id: 131 },
    { name: 'ditto', id: 132 },
    { name: 'eevee', id: 133 },
    { name: 'vaporeon', id: 134 },
    { name: 'jolteon', id: 135 },
    { name: 'flareon', id: 136 },
    { name: 'porygon', id: 137 },
    { name: 'omanyte', id: 138, evolvesTo: 139 },
    { name: 'omastar', id: 139 },
    { name: 'kabuto', id: 140, evolvesTo: 141 },
    { name: 'kabutops', id: 141 },
    { name: 'aerodactyl', id: 142 },
    { name: 'snorlax', id: 143 },
    { name: 'articuno', id: 144 },
    { name: 'zapdos', id: 145 },
    { name: 'moltres', id: 146 },
    { name: 'dratini', id: 147, evolvesTo: 148 },
    { name: 'dragonair', id: 148, evolvesTo: 149 },
    { name: 'dragonite', id: 149 },
    { name: 'mewtwo', id: 150 },
    { name: 'mew', id: 151 },
    // Gen 2
    { name: 'chikorita', id: 152, evolvesTo: 153 },
    { name: 'bayleef', id: 153, evolvesTo: 154 },
    { name: 'meganium', id: 154 },
    { name: 'cyndaquil', id: 155, evolvesTo: 156 },
    { name: 'quilava', id: 156, evolvesTo: 157 },
    { name: 'typhlosion', id: 157 },
    { name: 'totodile', id: 158, evolvesTo: 159 },
    { name: 'croconaw', id: 159, evolvesTo: 160 },
    { name: 'feraligatr', id: 160 },
    { name: 'sentret', id: 161, evolvesTo: 162 },
    { name: 'furret', id: 162 },
    { name: 'hoothoot', id: 163, evolvesTo: 164 },
    { name: 'noctowl', id: 164 },
    { name: 'ledyba', id: 165, evolvesTo: 166 },
    { name: 'ledian', id: 166 },
    { name: 'spinarak', id: 167, evolvesTo: 168 },
    { name: 'ariados', id: 168 },
    { name: 'crobat', id: 169 },
    { name: 'chinchou', id: 170, evolvesTo: 171 },
    { name: 'lanturn', id: 171 },
    { name: 'pichu', id: 172 },
    { name: 'cleffa', id: 173 },
    { name: 'igglybuff', id: 174 },
    { name: 'togepi', id: 175, evolvesTo: 176 },
    { name: 'togetic', id: 176 },
    { name: 'natu', id: 177, evolvesTo: 178 },
    { name: 'xatu', id: 178 },
    { name: 'mareep', id: 179, evolvesTo: 180 },
    { name: 'flaaffy', id: 180, evolvesTo: 181 },
    { name: 'ampharos', id: 181 },
    { name: 'bellossom', id: 182 },
    { name: 'marill', id: 183, evolvesTo: 184 },
    { name: 'azumarill', id: 184 },
    { name: 'sudowoodo', id: 185 },
    { name: 'politoed', id: 186 },
    { name: 'hoppip', id: 187, evolvesTo: 188 },
    { name: 'skiploom', id: 188, evolvesTo: 189 },
    { name: 'jumpluff', id: 189 },
    { name: 'aipom', id: 190 },
    { name: 'sunkern', id: 191, evolvesTo: 192 },
    { name: 'sunflora', id: 192 },
    { name: 'yanma', id: 193 },
    { name: 'wooper', id: 194, evolvesTo: 195 },
    { name: 'quagsire', id: 195 },
    { name: 'espeon', id: 196 },
    { name: 'umbreon', id: 197 },
    { name: 'murkrow', id: 198 },
    { name: 'slowking', id: 199 },
    { name: 'misdreavus', id: 200 },
    { name: 'unown', id: 201 },
    { name: 'wobbuffet', id: 202 },
    { name: 'girafarig', id: 203 },
    { name: 'pineco', id: 204, evolvesTo: 205 },
    { name: 'forretress', id: 205 },
    { name: 'dunsparce', id: 206 },
    { name: 'gligar', id: 207 },
    { name: 'steelix', id: 208 },
    { name: 'snubbull', id: 209, evolvesTo: 210 },
    { name: 'granbull', id: 210 },
    { name: 'qwilfish', id: 211 },
    { name: 'scizor', id: 212 },
    { name: 'shuckle', id: 213 },
    { name: 'heracross', id: 214 },
    { name: 'sneasel', id: 215 },
    { name: 'teddiursa', id: 216, evolvesTo: 217 },
    { name: 'ursaring', id: 217 },
    { name: 'slugma', id: 218, evolvesTo: 219 },
    { name: 'magcargo', id: 219 },
    { name: 'swinub', id: 220, evolvesTo: 221 },
    { name: 'piloswine', id: 221 },
    { name: 'corsola', id: 222 },
    { name: 'remoraid', id: 223, evolvesTo: 224 },
    { name: 'octillery', id: 224 },
    { name: 'delibird', id: 225 },
    { name: 'mantine', id: 226 },
    { name: 'skarmory', id: 227 },
    { name: 'houndour', id: 228, evolvesTo: 229 },
    { name: 'houndoom', id: 229 },
    { name: 'kingdra', id: 230 },
    { name: 'phanpy', id: 231, evolvesTo: 232 },
    { name: 'donphan', id: 232 },
    { name: 'porygon2', id: 233 },
    { name: 'stantler', id: 234 },
    { name: 'smeargle', id: 235 },
    { name: 'tyrogue', id: 236, evolvesTo: 237 },
    { name: 'hitmontop', id: 237 },
    { name: 'smoochum', id: 238 },
    { name: 'elekid', id: 239 },
    { name: 'magby', id: 240 },
    { name: 'miltank', id: 241 },
    { name: 'blissey', id: 242 },
    { name: 'raikou', id: 243 },
    { name: 'entei', id: 244 },
    { name: 'suicune', id: 245 },
    { name: 'larvitar', id: 246, evolvesTo: 247 },
    { name: 'pupitar', id: 247, evolvesTo: 248 },
    { name: 'tyranitar', id: 248 },
    { name: 'lugia', id: 249 },
    { name: 'ho-oh', id: 250 },
    { name: 'celebi', id: 251 },
    // Gen 3
    { name: 'treecko', id: 252, evolvesTo: 253 },
    { name: 'grovyle', id: 253, evolvesTo: 254 },
    { name: 'sceptile', id: 254 },
    { name: 'torchic', id: 255, evolvesTo: 256 },
    { name: 'combusken', id: 256, evolvesTo: 257 },
    { name: 'blaziken', id: 257 },
    { name: 'mudkip', id: 258, evolvesTo: 259 },
    { name: 'marshtomp', id: 259, evolvesTo: 260 },
    { name: 'swampert', id: 260 },
    { name: 'poochyena', id: 261, evolvesTo: 262 },
    { name: 'mightyena', id: 262 },
    { name: 'zigzagoon', id: 263, evolvesTo: 264 },
    { name: 'linoone', id: 264 },
    { name: 'wurmple', id: 265, evolvesTo: 266 },
    { name: 'silcoon', id: 266 },
    { name: 'beautifly', id: 267 },
    { name: 'cascoon', id: 268, evolvesTo: 269 },
    { name: 'dustox', id: 269 },
    { name: 'lotad', id: 270, evolvesTo: 271 },
    { name: 'lombre', id: 271, evolvesTo: 272 },
    { name: 'ludicolo', id: 272 },
    { name: 'seedot', id: 273, evolvesTo: 274 },
    { name: 'nuzleaf', id: 274, evolvesTo: 275 },
    { name: 'shiftry', id: 275 },
    { name: 'taillow', id: 276, evolvesTo: 277 },
    { name: 'swellow', id: 277 },
    { name: 'wingull', id: 278, evolvesTo: 279 },
    { name: 'pelipper', id: 279 },
    { name: 'ralts', id: 280, evolvesTo: 281 },
    { name: 'kirlia', id: 281, evolvesTo: 282 },
    { name: 'gardevoir', id: 282 },
    { name: 'surskit', id: 283, evolvesTo: 284 },
    { name: 'masquerain', id: 284 },
    { name: 'shroomish', id: 285, evolvesTo: 286 },
    { name: 'breloom', id: 286 },
    { name: 'slakoth', id: 287, evolvesTo: 288 },
    { name: 'vigoroth', id: 288, evolvesTo: 289 },
    { name: 'slaking', id: 289 },
    { name: 'nincada', id: 290, evolvesTo: 291 },
    { name: 'ninjask', id: 291 },
    { name: 'shedinja', id: 292 },
    { name: 'whismur', id: 293, evolvesTo: 294 },
    { name: 'loudred', id: 294, evolvesTo: 295 },
    { name: 'exploud', id: 295 },
    { name: 'makuhita', id: 296, evolvesTo: 297 },
    { name: 'hariyama', id: 297 },
    { name: 'azurill', id: 298 },
    { name: 'nosepass', id: 299 },
    { name: 'skitty', id: 300, evolvesTo: 301 },
    { name: 'delcatty', id: 301 },
    { name: 'sableye', id: 302 },
    { name: 'mawile', id: 303 },
    { name: 'aron', id: 304, evolvesTo: 305 },
    { name: 'lairon', id: 305, evolvesTo: 306 },
    { name: 'aggron', id: 306 },
    { name: 'meditite', id: 307, evolvesTo: 308 },
    { name: 'medicham', id: 308 },
    { name: 'electrike', id: 309, evolvesTo: 310 },
    { name: 'manectric', id: 310 },
    { name: 'plusle', id: 311 },
    { name: 'minun', id: 312 },
    { name: 'volbeat', id: 313 },
    { name: 'illumise', id: 314 },
    { name: 'roselia', id: 315 },
    { name: 'gulpin', id: 316, evolvesTo: 317 },
    { name: 'swalot', id: 317 },
    { name: 'carvanha', id: 318, evolvesTo: 319 },
    { name: 'sharpedo', id: 319 },
    { name: 'wailmer', id: 320, evolvesTo: 321 },
    { name: 'wailord', id: 321 },
    { name: 'numel', id: 322, evolvesTo: 323 },
    { name: 'camerupt', id: 323 },
    { name: 'torkoal', id: 324 },
    { name: 'spoink', id: 325, evolvesTo: 326 },
    { name: 'grumpig', id: 326 },
    { name: 'spinda', id: 327 },
    { name: 'trapinch', id: 328, evolvesTo: 329 },
    { name: 'vibrava', id: 329, evolvesTo: 330 },
    { name: 'flygon', id: 330 },
    { name: 'cacnea', id: 331, evolvesTo: 332 },
    { name: 'cacturne', id: 332 },
    { name: 'swablu', id: 333, evolvesTo: 334 },
    { name: 'altaria', id: 334 },
    { name: 'zangoose', id: 335 },
    { name: 'seviper', id: 336 },
    { name: 'lunatone', id: 337 },
    { name: 'solrock', id: 338 },
    { name: 'barboach', id: 339, evolvesTo: 340 },
    { name: 'whiscash', id: 340 },
    { name: 'corphish', id: 341, evolvesTo: 342 },
    { name: 'crawdaunt', id: 342 },
    { name: 'baltoy', id: 343, evolvesTo: 344 },
    { name: 'claydol', id: 344 },
    { name: 'lileep', id: 345, evolvesTo: 346 },
    { name: 'cradily', id: 346 },
    { name: 'anorith', id: 347, evolvesTo: 348 },
    { name: 'armaldo', id: 348 },
    { name: 'feebas', id: 349, evolvesTo: 350 },
    { name: 'milotic', id: 350 },
    { name: 'castform', id: 351 },
    { name: 'kecleon', id: 352 },
    { name: 'shuppet', id: 353, evolvesTo: 354 },
    { name: 'banette', id: 354 },
    { name: 'duskull', id: 355, evolvesTo: 356 },
    { name: 'dusclops', id: 356 },
    { name: 'tropius', id: 357 },
    { name: 'chimecho', id: 358 },
    { name: 'absol', id: 359 },
    { name: 'wynaut', id: 360 },
    { name: 'snorunt', id: 361, evolvesTo: 362 },
    { name: 'glalie', id: 362 },
    { name: 'spheal', id: 363, evolvesTo: 364 },
    { name: 'sealeo', id: 364, evolvesTo: 365 },
    { name: 'walrein', id: 365 },
    { name: 'clamperl', id: 366 },
    { name: 'huntail', id: 367 },
    { name: 'gorebyss', id: 368 },
    { name: 'relicanth', id: 369 },
    { name: 'luvdisc', id: 370 },
    { name: 'bagon', id: 371, evolvesTo: 372 },
    { name: 'shelgon', id: 372, evolvesTo: 373 },
    { name: 'salamence', id: 373 },
    { name: 'beldum', id: 374, evolvesTo: 375 },
    { name: 'metang', id: 375, evolvesTo: 376 },
    { name: 'metagross', id: 376 },
    { name: 'regirock', id: 377 },
    { name: 'regice', id: 378 },
    { name: 'registeel', id: 379 },
    { name: 'latias', id: 380 },
    { name: 'latios', id: 381 },
    { name: 'kyogre', id: 382 },
    { name: 'groudon', id: 383 },
    { name: 'rayquaza', id: 384 },
    { name: 'jirachi', id: 385 },
    { name: 'deoxys-normal', id: 386 },
    // Gen 4
    { name: 'turtwig', id: 387, evolvesTo: 388 },
    { name: 'grotle', id: 388, evolvesTo: 389 },
    { name: 'torterra', id: 389 },
    { name: 'chimchar', id: 390, evolvesTo: 391 },
    { name: 'monferno', id: 391, evolvesTo: 392 },
    { name: 'infernape', id: 392 },
    { name: 'piplup', id: 393, evolvesTo: 394 },
    { name: 'prinplup', id: 394, evolvesTo: 395 },
    { name: 'empoleon', id: 395 },
    { name: 'starly', id: 396, evolvesTo: 397 },
    { name: 'staravia', id: 397, evolvesTo: 398 },
    { name: 'staraptor', id: 398 },
    { name: 'bidoof', id: 399, evolvesTo: 400 },
    { name: 'bibarel', id: 400 },
    { name: 'kricketot', id: 401, evolvesTo: 402 },
    { name: 'kricketune', id: 402 },
    { name: 'shinx', id: 403, evolvesTo: 404 },
    { name: 'luxio', id: 404, evolvesTo: 405 },
    { name: 'luxray', id: 405 },
    { name: 'budew', id: 406 },
    { name: 'roserade', id: 407 },
    { name: 'cranidos', id: 408, evolvesTo: 409 },
    { name: 'rampardos', id: 409 },
    { name: 'shieldon', id: 410, evolvesTo: 411 },
    { name: 'bastiodon', id: 411 },
    { name: 'burmy', id: 412, evolvesTo: 413 },
    { name: 'wormadam', id: 413 },
    { name: 'mothim', id: 414 },
    { name: 'combee', id: 415, evolvesTo: 416 },
    { name: 'vespiquen', id: 416 },
    { name: 'pachirisu', id: 417 },
    { name: 'buizel', id: 418, evolvesTo: 419 },
    { name: 'floatzel', id: 419 },
    { name: 'cherubi', id: 420, evolvesTo: 421 },
    { name: 'cherrim', id: 421 },
    { name: 'shellos', id: 422, evolvesTo: 423 },
    { name: 'gastrodon', id: 423 },
    { name: 'ambipom', id: 424 },
    { name: 'drifloon', id: 425, evolvesTo: 426 },
    { name: 'drifblim', id: 426 },
    { name: 'buneary', id: 427, evolvesTo: 428 },
    { name: 'lopunny', id: 428 },
    { name: 'mismagius', id: 429 },
    { name: 'honchkrow', id: 430 },
    { name: 'glameow', id: 431, evolvesTo: 432 },
    { name: 'purugly', id: 432 },
    { name: 'chingling', id: 433 },
    { name: 'stunky', id: 434, evolvesTo: 435 },
    { name: 'skuntank', id: 435 },
    { name: 'bronzor', id: 436, evolvesTo: 437 },
    { name: 'bronzong', id: 437 },
    { name: 'bonsly', id: 438 },
    { name: 'mime-jr', id: 439 },
    { name: 'happiny', id: 440 },
    { name: 'chatot', id: 441 },
    { name: 'spiritomb', id: 442 },
    { name: 'gible', id: 443, evolvesTo: 444 },
    { name: 'gabite', id: 444, evolvesTo: 445 },
    { name: 'garchomp', id: 445 },
    { name: 'munchlax', id: 446 },
    { name: 'riolu', id: 447, evolvesTo: 448 },
    { name: 'lucario', id: 448 },
    { name: 'hippopotas', id: 449, evolvesTo: 450 },
    { name: 'hippowdon', id: 450 },
  
    { name: 'bulbasaur', id: 1 },
    { name: 'ivysaur', id: 2 },
    { name: 'venusaur', id: 3 },
    { name: 'charmander', id: 4 },
    { name: 'charmeleon', id: 5 },
    { name: 'charizard', id: 6 },
    { name: 'squirtle', id: 7 },
    { name: 'wartortle', id: 8 },
    { name: 'blastoise', id: 9 },
    { name: 'caterpie', id: 10 },
    { name: 'metapod', id: 11 },
    { name: 'butterfree', id: 12 },
    { name: 'weedle', id: 13 },
    { name: 'kakuna', id: 14 },
    { name: 'beedrill', id: 15 },
    { name: 'pidgey', id: 16 },
    { name: 'pidgeotto', id: 17 },
    { name: 'pidgeot', id: 18 },
    { name: 'rattata', id: 19 },
    { name: 'raticate', id: 20 },
    { name: 'spearow', id: 21 },
    { name: 'fearow', id: 22 },
    { name: 'ekans', id: 23 },
    { name: 'arbok', id: 24 },
    { name: 'pikachu', id: 25 },
    { name: 'raichu', id: 26 },
    { name: 'sandshrew', id: 27 },
    { name: 'sandslash', id: 28 },
    { name: 'nidoran-f', id: 29 },
    { name: 'nidorina', id: 30 },
    { name: 'nidoqueen', id: 31 },
    { name: 'nidoran-m', id: 32 },
    { name: 'nidorino', id: 33 },
    { name: 'nidoking', id: 34 },
    { name: 'clefairy', id: 35 },
    { name: 'clefable', id: 36 },
    { name: 'vulpix', id: 37 },
    { name: 'ninetales', id: 38 },
    { name: 'jigglypuff', id: 39 },
    { name: 'wigglytuff', id: 40 },
    { name: 'zubat', id: 41 },
    { name: 'golbat', id: 42 },
    { name: 'oddish', id: 43 },
    { name: 'gloom', id: 44 },
    { name: 'vileplume', id: 45 },
    { name: 'paras', id: 46 },
    { name: 'parasect', id: 47 },
    { name: 'venonat', id: 48 },
    { name: 'venomoth', id: 49 },
    { name: 'diglett', id: 50 },
    // ...
    // (Pokémon 51 through 450, see next step for full list)
  
    { name: 'bulbasaur', id: 1 },
    { name: 'ivysaur', id: 2 },
    { name: 'venusaur', id: 3 },
    { name: 'charmander', id: 4 },
    { name: 'charmeleon', id: 5 },
    { name: 'charizard', id: 6 },
    { name: 'squirtle', id: 7 },
    { name: 'wartortle', id: 8 },
    { name: 'blastoise', id: 9 },
    { name: 'caterpie', id: 10 },
    { name: 'metapod', id: 11 },
    { name: 'butterfree', id: 12 },
    { name: 'weedle', id: 13 },
    { name: 'kakuna', id: 14 },
    { name: 'beedrill', id: 15 },
    { name: 'pidgey', id: 16 },
    { name: 'pidgeotto', id: 17 },
    { name: 'pidgeot', id: 18 },
    { name: 'rattata', id: 19 },
    { name: 'raticate', id: 20 },
    { name: 'spearow', id: 21 },
    { name: 'fearow', id: 22 },
    { name: 'ekans', id: 23 },
    { name: 'arbok', id: 24 },
    { name: 'pikachu', id: 25 },
    { name: 'raichu', id: 26 },
    { name: 'sandshrew', id: 27 },
    { name: 'sandslash', id: 28 },
    { name: 'nidoran-f', id: 29 },
    { name: 'nidorina', id: 30 },
    { name: 'nidoqueen', id: 31 },
    { name: 'nidoran-m', id: 32 },
    { name: 'nidorino', id: 33 },
    { name: 'nidoking', id: 34 },
    { name: 'clefairy', id: 35 },
    { name: 'clefable', id: 36 },
    { name: 'vulpix', id: 37 },
    { name: 'ninetales', id: 38 },
    { name: 'jigglypuff', id: 39 },
    { name: 'wigglytuff', id: 40 },
    { name: 'zubat', id: 41 },
    { name: 'golbat', id: 42 },
    { name: 'oddish', id: 43 },
    { name: 'gloom', id: 44 },
    { name: 'vileplume', id: 45 },
    { name: 'paras', id: 46 },
    { name: 'parasect', id: 47 },
    { name: 'venonat', id: 48 },
    { name: 'venomoth', id: 49 },
    { name: 'diglett', id: 50 },
    { name: 'dugtrio', id: 51 },
    { name: 'meowth', id: 52 },
    { name: 'persian', id: 53 },
    { name: 'psyduck', id: 54 },
    { name: 'golduck', id: 55 },
    { name: 'mankey', id: 56 },
    { name: 'primeape', id: 57 },
    { name: 'growlithe', id: 58 },
    { name: 'arcanine', id: 59 },
    { name: 'poliwag', id: 60 },
    { name: 'poliwhirl', id: 61 },
    { name: 'poliwrath', id: 62 },
    { name: 'abra', id: 63 },
    { name: 'kadabra', id: 64 },
    { name: 'alakazam', id: 65 },
    { name: 'machop', id: 66 },
    { name: 'machoke', id: 67 },
    { name: 'machamp', id: 68 },
    { name: 'bellsprout', id: 69 },
    { name: 'weepinbell', id: 70 },
    { name: 'victreebel', id: 71 },
    { name: 'tentacool', id: 72 },
    { name: 'tentacruel', id: 73 },
    { name: 'geodude', id: 74 },
    { name: 'graveler', id: 75 },
    { name: 'golem', id: 76 },
    { name: 'ponyta', id: 77 },
    { name: 'rapidash', id: 78 },
    { name: 'slowpoke', id: 79 },
    { name: 'slowbro', id: 80 },
    { name: 'magnemite', id: 81 },
    { name: 'magneton', id: 82 },
    { name: 'farfetchd', id: 83 },
    { name: 'doduo', id: 84 },
    { name: 'dodrio', id: 85 },
    { name: 'seel', id: 86 },
    { name: 'dewgong', id: 87 },
    { name: 'grimer', id: 88 },
    { name: 'muk', id: 89 },
    { name: 'shellder', id: 90 },
    { name: 'cloyster', id: 91 },
    { name: 'gastly', id: 92 },
    { name: 'haunter', id: 93 },
    { name: 'gengar', id: 94 },
    { name: 'onix', id: 95 },
    { name: 'drowzee', id: 96 },
    { name: 'hypno', id: 97 },
    { name: 'krabby', id: 98 },
    { name: 'kingler', id: 99 },
    { name: 'voltorb', id: 100 },
    { name: 'electrode', id: 101 },
    { name: 'exeggcute', id: 102 },
    { name: 'exeggutor', id: 103 },
    { name: 'cubone', id: 104 },
    { name: 'marowak', id: 105 },
    { name: 'hitmonlee', id: 106 },
    { name: 'hitmonchan', id: 107 },
    { name: 'lickitung', id: 108 },
    { name: 'koffing', id: 109 },
    { name: 'weezing', id: 110 },
    { name: 'rhyhorn', id: 111 },
    { name: 'rhydon', id: 112 },
    { name: 'chansey', id: 113 },
    { name: 'tangela', id: 114 },
    { name: 'kangaskhan', id: 115 },
    { name: 'horsea', id: 116 },
    { name: 'seadra', id: 117 },
    { name: 'goldeen', id: 118 },
    { name: 'seaking', id: 119 },
    { name: 'staryu', id: 120 },
    { name: 'starmie', id: 121 },
    { name: 'mr-mime', id: 122 },
    { name: 'scyther', id: 123 },
    { name: 'jynx', id: 124 },
    { name: 'electabuzz', id: 125 },
    { name: 'magmar', id: 126 },
    { name: 'pinsir', id: 127 },
    { name: 'tauros', id: 128 },
    { name: 'magikarp', id: 129 },
    { name: 'gyarados', id: 130 },
    { name: 'lapras', id: 131 },
    { name: 'ditto', id: 132 },
    { name: 'eevee', id: 133 },
    { name: 'vaporeon', id: 134 },
    { name: 'jolteon', id: 135 },
    { name: 'flareon', id: 136 },
    { name: 'porygon', id: 137 },
    { name: 'omanyte', id: 138 },
    { name: 'omastar', id: 139 },
    { name: 'kabuto', id: 140 },
    { name: 'kabutops', id: 141 },
    { name: 'aerodactyl', id: 142 },
    { name: 'snorlax', id: 143 },
    { name: 'articuno', id: 144 },
    { name: 'zapdos', id: 145 },
    { name: 'moltres', id: 146 },
    { name: 'dratini', id: 147 },
    { name: 'dragonair', id: 148 },
    { name: 'dragonite', id: 149 },
    { name: 'mewtwo', id: 150 },
    { name: 'mew', id: 151 }
];

export function getPokemonImageUrl(id: number): string {
  return `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/${id}.png`;
}
