import * as stylex from '@stylexjs/stylex';

export const styles = stylex.create({
  container: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    background: '#fff',
    textAlign: 'center',
  },
  heading: {
    fontSize: 36,
    marginBottom: 8,
    fontWeight: 700,
  },
  subheading: {
    fontSize: 28,
    marginBottom: 12,
    fontWeight: 500,
  },
  playerRow: {
    margin: 8,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  playerInput: {
    fontSize: 24,
    width: 400,
    padding: 24,
  },
  removeBtn: {
    fontSize: 24,
    marginLeft: 8,
  },
  addPlayerBtn: {
    fontFamily: "'Press Start 2P', 'Courier New', Courier, monospace",
    fontSize: 24,
    padding: '24px 64px',
    borderRadius: 0,
    background: '#eee',
    border: '7px solid #aaa',
    color: '#000',
    cursor: 'pointer',
    marginTop: 12,
    transition: 'background 0.15s, color 0.15s',
  },
  modeLabel: {
    textAlign: 'left',
  },
  optionLabel: {
    width: 200,
    display: 'inline-block'
  },
  modeSelect: {
    fontFamily: "'Press Start 2P', 'Courier New', Courier, monospace",
    fontSize: 24,
    marginLeft: 8,
    padding: '16px 24px',
    borderRadius: 0,
    background: '#eee',
    border: '7px solid #aaa',
    color: '#000',
    cursor: 'pointer',
    transition: 'background 0.15s, color 0.15s',
    width: 312,
  },
  optionsContainer: {
    marginTop: 36,
    marginBottom: 36,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  roundsRow: {
    margin: 16,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  roundsLabel: {
    textAlign: 'left',
  },
  roundsInput: {
    fontFamily: "'Press Start 2P', 'Courier New', Courier, monospace",
    fontSize: 24,
    marginLeft: 8,
    padding: '16px 24px',
    borderRadius: 0,
    background: '#eee',
    border: '7px solid #aaa',
    color: '#000',
    cursor: 'pointer',
    transition: 'background 0.15s, color 0.15s',
    width: 250,
  },
  startBtn: {
    fontFamily: "'Press Start 2P', 'Courier New', Courier, monospace",
    fontSize: 36,
    padding: '24px 64px',
    borderRadius: 0,
    background: '#eee',
    border: '7px solid #aaa',
    color: '#000',
    cursor: 'pointer',
    marginTop: 24,
    transition: 'background 0.15s, color 0.15s',
  },
});
